<center>
<table border="0" cellspacing='0' cellpadding='0'>
	<td>

<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://active.macromedia.com/flash4/cabs/swflash.cab#version=4,0,0,0" id="swish_main" width="558" height="65">
            <param name="movie" value="http://www.vasst.com/swish_main.swf">
            <param name="quality" value="high">
            <param name="bgcolor" value="#FFFFFF">
            <embed name="swish_main" src="http://www.vasst.com/swish_main.swf" quality="high" bgcolor="#FFFFFF" width="558" height="65" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">
</embed></object>
	</td>
	<td align="center" width="200" background="./images/logo_back.gif">
	<a href="http://www.vasst.com/"><img src="./images/logo_vasst-grey.gif" border="0"></a>
	</td>
</table>
</center>