<center><table>
<tr>
	<td valign='top'>
<a href='http://www.sundancemediagroup.com/aboutvasst.htm' target=_new><img src='http://www.sundancemediagroup.com/VASTpix/vasstanime[1].gif' height='82' width='215' border='0'>
	</td>
	<td valign='top' class='AdBox' width='215' style='background-color: #0099FF; color: #000000;'>
<font color="#000000" size="2"><a style="color: #000000" href="http://www.vasst.com/">VASST tour for Sony's Vegas 5 announced.</a></font>
	</td>
</table></center>