<div class='PageHeader'>
<table width='100%' cellspacing='0' cellpadding='0' border='0'><tr>
<td valign='top' height='100'><embed width="545" height="80" src="/images/sundancemenu.swf"><noembed>You'll need FLASH to view this menu</noembed></td>
<td valign='top' height='100'><a href='http://www.sundancemediagroup.com/aboutvasst.htm' target=_new><img src='http://www.sundancemediagroup.com/VASTpix/vasstanime[1].gif' height='82' width='215' border='0'></td>
<td><font color="#C0C0C0" size="2">Check out the announcement of the Sony VASST tour on the VASST website.
<a href='http://www.vasst.com' target=_new></font></p>
<p>
<a href="http://www.dmnforums.com/cgi-bin/disp.fcgi?dire=4&prog=displaywwugindex.fcgi&endday=14&forum=sonic-foundry_vegas">
    <img alt src="http://www.sundancemediagroup.com/training/menulogo_r1_c2.gif" border="0" name="menulogo_r1_c2" width="89" height="52"></a></td>
</table>
</div>

<%' ReplaceNull(Application(g_sCACHE_HEADER), g_sDEFAULT_HEADER) %>